version: '2'

services:
  zookeeper:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    image: apache/kafka
    ports:
      - "9092:9092"



